{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(numPizzasSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizzas Sold"
    },
    {
     "expr": "rate(createPizzaFailures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Creation Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(totalRevenue_ratio{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "latency_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Services"
    },
    {
     "expr": "pizzaLatency_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Authentication Fails&Success/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(successfulAuths_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(failedAuths_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(activeUsers_total{source=\"jwt-pizza-service\"}[30s])",
     "legendFormat": "activeUsers"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(requests_per_method_total{method=\"GET\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(requests_per_method_total{method=\"POST\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(requests_per_method_total{method=\"PUT\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(requests_per_method_total{method=\"DELETE\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(numRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "TOTAL"
    }
   ]
  }
 ]
}